# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fast_typeMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.stackedWidget.setObjectName("stackedWidget")
        self.Main = QtWidgets.QWidget()
        self.Main.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(188, 255, 199, 255), stop:1 rgba(174, 231, 255, 255));")
        self.Main.setObjectName("Main")
        self.type = QtWidgets.QLabel(self.Main)
        self.type.setGeometry(QtCore.QRect(650, 70, 131, 131))
        self.type.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                "font: 60pt \"Agency FB\";")
        self.type.setObjectName("type")
        self.Fast = QtWidgets.QLabel(self.Main)
        self.Fast.setGeometry(QtCore.QRect(440, 70, 181, 121))
        self.Fast.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                "font: 65pt \"Dancing Script\";\n"
                                "\n"
                                "\n"
                                "\n"
                                "")
        self.Fast.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.Fast.setObjectName("Fast")
        self.lrn = QtWidgets.QPushButton(self.Main)
        self.lrn.setGeometry(QtCore.QRect(400, 280, 421, 121))
        self.lrn.setStyleSheet("QPushButton{\n"
                               "    background-color: rgb(255, 203, 185);\n"
                               "    font: 57 20pt \"Montserrat Medium\";\n"
                               "    border-radius: 20px;\n"
                               "}\n"
                               "\n"
                               "QPushButton:hover {\n"
                               "    font-size: 22pt;   \n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed {\n"
                               "    background-color: rgb(229, 182, 166);       \n"
                               "}")
        self.lrn.setObjectName("lrn")
        self.gm = QtWidgets.QPushButton(self.Main)
        self.gm.setGeometry(QtCore.QRect(750, 470, 341, 121))
        self.gm.setStyleSheet("QPushButton{\n"
                              "    background-color: rgb(255, 203, 185);\n"
                              "    font: 57 20pt \"Montserrat Medium\";\n"
                              "    border-radius: 20px;\n"
                              "}\n"
                              "\n"
                              "QPushButton:hover {\n"
                              "    font-size: 22pt;   \n"
                              "}\n"
                              "\n"
                              "QPushButton:pressed {\n"
                              "    background-color: rgb(229, 182, 166);       \n"
                              "}\n"
                              "")
        self.gm.setObjectName("gm")
        self.ex = QtWidgets.QPushButton(self.Main)
        self.ex.setGeometry(QtCore.QRect(140, 470, 341, 121))
        self.ex.setStyleSheet("QPushButton{\n"
                              "    background-color: rgb(255, 203, 185);\n"
                              "    font: 57 20pt \"Montserrat Medium\";\n"
                              "    border-radius: 20px;\n"
                              "}\n"
                              "\n"
                              "QPushButton:hover {\n"
                              "    font-size: 22pt;   \n"
                              "}\n"
                              "\n"
                              "QPushButton:pressed {\n"
                              "    background-color: rgb(229, 182, 166);       \n"
                              "}")
        self.ex.setObjectName("ex")
        self.stackedWidget.addWidget(self.Main)
        self.Learning = QtWidgets.QWidget()
        self.Learning.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(188, 255, 199, 255), stop:1 rgba(174, 231, 255, 255));")
        self.Learning.setObjectName("Learning")
        self.label_6 = QtWidgets.QLabel(self.Learning)
        self.label_6.setGeometry(QtCore.QRect(520, 60, 271, 61))
        self.label_6.setStyleSheet("font: 30pt \"Montserrat Medium\";\n"
                                   "background-color:  rgba(188, 255, 199, 0)")
        self.label_6.setObjectName("label_6")
        self.lvl_1 = QtWidgets.QPushButton(self.Learning)
        self.lvl_1.setGeometry(QtCore.QRect(70, 180, 241, 121))
        self.lvl_1.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.lvl_1.setObjectName("lvl_1")
        self.lvl_2 = QtWidgets.QPushButton(self.Learning)
        self.lvl_2.setGeometry(QtCore.QRect(370, 180, 241, 121))
        self.lvl_2.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.lvl_2.setObjectName("lvl_2")
        self.lvl_3 = QtWidgets.QPushButton(self.Learning)
        self.lvl_3.setGeometry(QtCore.QRect(670, 180, 241, 121))
        self.lvl_3.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.lvl_3.setObjectName("lvl_3")
        self.lvl_4 = QtWidgets.QPushButton(self.Learning)
        self.lvl_4.setGeometry(QtCore.QRect(980, 180, 241, 121))
        self.lvl_4.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}\n"
                                 "")
        self.lvl_4.setObjectName("lvl_4")
        self.lvl_5 = QtWidgets.QPushButton(self.Learning)
        self.lvl_5.setGeometry(QtCore.QRect(70, 350, 241, 121))
        self.lvl_5.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.lvl_5.setObjectName("lvl_5")
        self.lvl_8 = QtWidgets.QPushButton(self.Learning)
        self.lvl_8.setGeometry(QtCore.QRect(980, 350, 241, 121))
        self.lvl_8.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.lvl_8.setObjectName("lvl_8")
        self.lvl_7 = QtWidgets.QPushButton(self.Learning)
        self.lvl_7.setGeometry(QtCore.QRect(670, 350, 241, 121))
        self.lvl_7.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.lvl_7.setObjectName("lvl_7")
        self.lvl_6 = QtWidgets.QPushButton(self.Learning)
        self.lvl_6.setGeometry(QtCore.QRect(370, 350, 241, 121))
        self.lvl_6.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.lvl_6.setObjectName("lvl_6")
        self.lvl_12 = QtWidgets.QPushButton(self.Learning)
        self.lvl_12.setGeometry(QtCore.QRect(980, 530, 241, 121))
        self.lvl_12.setStyleSheet("QPushButton{\n"
                                  "    background-color: rgb(255, 203, 185);\n"
                                  "    font: 15pt \"Montserrat Medium\";\n"
                                  "    border-radius: 20px;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:hover {\n"
                                  "    font-size: 17pt;   \n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed {\n"
                                  "    background-color: rgb(229, 182, 166);       \n"
                                  "}")
        self.lvl_12.setObjectName("lvl_12")
        self.lvl_9 = QtWidgets.QPushButton(self.Learning)
        self.lvl_9.setGeometry(QtCore.QRect(70, 530, 241, 121))
        self.lvl_9.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.lvl_9.setObjectName("lvl_9")
        self.lvl_10 = QtWidgets.QPushButton(self.Learning)
        self.lvl_10.setGeometry(QtCore.QRect(370, 530, 241, 121))
        self.lvl_10.setStyleSheet("QPushButton{\n"
                                  "    background-color: rgb(255, 203, 185);\n"
                                  "    font: 15pt \"Montserrat Medium\";\n"
                                  "    border-radius: 20px;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:hover {\n"
                                  "    font-size: 17pt;   \n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed {\n"
                                  "    background-color: rgb(229, 182, 166);       \n"
                                  "}")
        self.lvl_10.setObjectName("lvl_10")
        self.lvl_11 = QtWidgets.QPushButton(self.Learning)
        self.lvl_11.setGeometry(QtCore.QRect(670, 530, 241, 121))
        self.lvl_11.setStyleSheet("QPushButton{\n"
                                  "    background-color: rgb(255, 203, 185);\n"
                                  "    font: 15pt \"Montserrat Medium\";\n"
                                  "    border-radius: 20px;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:hover {\n"
                                  "    font-size: 17pt;   \n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed {\n"
                                  "    background-color: rgb(229, 182, 166);       \n"
                                  "}")
        self.lvl_11.setObjectName("lvl_11")
        self.stackedWidget.addWidget(self.Learning)
        self.Exercise = QtWidgets.QWidget()
        self.Exercise.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(188, 255, 199, 255), stop:1 rgba(174, 231, 255, 255));")
        self.Exercise.setObjectName("Exercise")
        self.label_8 = QtWidgets.QLabel(self.Exercise)
        self.label_8.setGeometry(QtCore.QRect(480, 50, 321, 61))
        self.label_8.setStyleSheet("font: 30pt \"Montserrat Medium\";\n"
                                   "background-color:  rgba(188, 255, 199, 0)")
        self.label_8.setObjectName("label_8")
        self.time = QtWidgets.QPushButton(self.Exercise)
        self.time.setGeometry(QtCore.QRect(60, 350, 341, 121))
        self.time.setStyleSheet("QPushButton{\n"
                                "    background-color: rgb(255, 203, 185);\n"
                                "    font: 15pt \"Montserrat Medium\";\n"
                                "    border-radius: 20px;\n"
                                "}\n"
                                "\n"
                                "QPushButton:hover {\n"
                                "    font-size: 17pt;   \n"
                                "}\n"
                                "\n"
                                "QPushButton:pressed {\n"
                                "    background-color: rgb(229, 182, 166);       \n"
                                "}")
        self.time.setObjectName("time")
        self.comboBox = QtWidgets.QComboBox(self.Exercise)
        self.comboBox.setGeometry(QtCore.QRect(510, 200, 261, 31))
        self.comboBox.setStyleSheet(" border-radius: 5px;\n"
                                    "background-color: white;\n"
                                    "font: 10pt \"Roboto\";")
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.choose_1 = QtWidgets.QLabel(self.Exercise)
        self.choose_1.setGeometry(QtCore.QRect(510, 150, 271, 31))
        self.choose_1.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
                                    "font: 11pt \"Roboto\";")
        self.choose_1.setObjectName("choose_1")
        self.story = QtWidgets.QPushButton(self.Exercise)
        self.story.setGeometry(QtCore.QRect(470, 350, 341, 121))
        self.story.setStyleSheet("QPushButton{\n"
                                 "    background-color: rgb(255, 203, 185);\n"
                                 "    font: 15pt \"Montserrat Medium\";\n"
                                 "    border-radius: 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size: 17pt;   \n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(229, 182, 166);       \n"
                                 "}")
        self.story.setObjectName("story")
        self.inf = QtWidgets.QPushButton(self.Exercise)
        self.inf.setGeometry(QtCore.QRect(880, 350, 341, 121))
        self.inf.setStyleSheet("QPushButton{\n"
                               "    background-color: rgb(255, 203, 185);\n"
                               "    font: 15pt \"Montserrat Medium\";\n"
                               "    border-radius: 20px;\n"
                               "}\n"
                               "\n"
                               "QPushButton:hover {\n"
                               "    font-size: 17pt;   \n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed {\n"
                               "    background-color: rgb(229, 182, 166);       \n"
                               "}")
        self.inf.setObjectName("inf")
        self.stackedWidget.addWidget(self.Exercise)
        self.Games = QtWidgets.QWidget()
        self.Games.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(188, 255, 199, 255), stop:1 rgba(174, 231, 255, 255));")
        self.Games.setObjectName("Games")
        self.label_9 = QtWidgets.QLabel(self.Games)
        self.label_9.setGeometry(QtCore.QRect(570, 50, 151, 61))
        self.label_9.setStyleSheet("font: 30pt \"Montserrat Medium\";\n"
                                   "background-color:  rgba(188, 255, 199, 0)")
        self.label_9.setObjectName("label_9")
        self.comboBox_2 = QtWidgets.QComboBox(self.Games)
        self.comboBox_2.setGeometry(QtCore.QRect(510, 200, 261, 31))
        self.comboBox_2.setStyleSheet(" border-radius: 5px;\n"
                                      "background-color: white;\n"
                                      "font: 10pt \"Roboto\";")
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.choose_2 = QtWidgets.QLabel(self.Games)
        self.choose_2.setGeometry(QtCore.QRect(510, 150, 271, 31))
        self.choose_2.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
                                    "font: 11pt \"Roboto\";")
        self.choose_2.setObjectName("choose_2")
        self.hear = QtWidgets.QPushButton(self.Games)
        self.hear.setGeometry(QtCore.QRect(60, 350, 341, 121))
        self.hear.setStyleSheet("QPushButton{\n"
                                "    background-color: rgb(255, 203, 185);\n"
                                "    font: 15pt \"Montserrat Medium\";\n"
                                "    border-radius: 20px;\n"
                                "}\n"
                                "\n"
                                "QPushButton:hover {\n"
                                "    font-size: 17pt;   \n"
                                "}\n"
                                "\n"
                                "QPushButton:pressed {\n"
                                "    background-color: rgb(229, 182, 166);       \n"
                                "}")
        self.hear.setObjectName("hear")
        self.pack = QtWidgets.QPushButton(self.Games)
        self.pack.setGeometry(QtCore.QRect(880, 350, 341, 121))
        self.pack.setStyleSheet("QPushButton{\n"
                                "    background-color: rgb(255, 203, 185);\n"
                                "    font: 15pt \"Montserrat Medium\";\n"
                                "    border-radius: 20px;\n"
                                "}\n"
                                "\n"
                                "QPushButton:hover {\n"
                                "    font-size: 17pt;   \n"
                                "}\n"
                                "\n"
                                "QPushButton:pressed {\n"
                                "    background-color: rgb(229, 182, 166);       \n"
                                "}")
        self.pack.setObjectName("pack")
        self.rain = QtWidgets.QPushButton(self.Games)
        self.rain.setGeometry(QtCore.QRect(470, 350, 341, 121))
        self.rain.setStyleSheet("QPushButton{\n"
                                "    background-color: rgb(255, 203, 185);\n"
                                "    font: 15pt \"Montserrat Medium\";\n"
                                "    border-radius: 20px;\n"
                                "}\n"
                                "\n"
                                "QPushButton:hover {\n"
                                "    font-size: 17pt;   \n"
                                "}\n"
                                "\n"
                                "QPushButton:pressed {\n"
                                "    background-color: rgb(229, 182, 166);       \n"
                                "}")
        self.rain.setObjectName("rain")
        self.stackedWidget.addWidget(self.Games)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.type.setText(_translate("MainWindow", "type"))
        self.Fast.setText(_translate("MainWindow", "Fast"))
        self.lrn.setText(_translate("MainWindow", "Обучение"))
        self.gm.setText(_translate("MainWindow", "Игры"))
        self.ex.setText(_translate("MainWindow", "Тренировка"))
        self.label_6.setText(_translate("MainWindow", "Обучение"))
        self.lvl_1.setText(_translate("MainWindow", "Уровень 1"))
        self.lvl_2.setText(_translate("MainWindow", "Уровень 2"))
        self.lvl_3.setText(_translate("MainWindow", "Уровень 3"))
        self.lvl_4.setText(_translate("MainWindow", "Уровень 4"))
        self.lvl_5.setText(_translate("MainWindow", "Уровень 5"))
        self.lvl_8.setText(_translate("MainWindow", "Уровень 8"))
        self.lvl_7.setText(_translate("MainWindow", "Уровень 7"))
        self.lvl_6.setText(_translate("MainWindow", "Уровень 6"))
        self.lvl_12.setText(_translate("MainWindow", "Уровень 12"))
        self.lvl_9.setText(_translate("MainWindow", "Уровень 9"))
        self.lvl_10.setText(_translate("MainWindow", "Уровень 10"))
        self.lvl_11.setText(_translate("MainWindow", "Уровень 11"))
        self.label_8.setText(_translate("MainWindow", "Тренировка"))
        self.time.setText(_translate("MainWindow", "На время"))
        self.comboBox.setCurrentText(_translate("MainWindow", "Низкий"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Низкий"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Средний"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Высокий"))
        self.choose_1.setText(_translate("MainWindow", "Выберите уровень подготовки:"))
        self.story.setText(_translate("MainWindow", "Истории"))
        self.inf.setText(_translate("MainWindow", "Бесконечный"))
        self.label_9.setText(_translate("MainWindow", "Игры"))
        self.comboBox_2.setCurrentText(_translate("MainWindow", "Низкий"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Низкий"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Средний"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Высокий"))
        self.choose_2.setText(_translate("MainWindow", "Выберите уровень подготовки:"))
        self.hear.setText(_translate("MainWindow", "На слух"))
        self.pack.setText(_translate("MainWindow", "Пакмен"))
        self.rain.setText(_translate("MainWindow", "Дождь"))

        self.lrn.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))
        self.ex.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))
        self.gm.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(3))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
