# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Learning.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from datetime import datetime
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Fast_type(object):
    def setupUi(self, Fast_type):
        Fast_type.setObjectName("Fast_type")
        Fast_type.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(Fast_type)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1280, 730))
        self.stackedWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(188, 255, 199, 255), stop:1 rgba(174, 231, 255, 255));")
        self.stackedWidget.setObjectName("stackedWidget")
        self.lvl_1 = QtWidgets.QWidget()
        self.lvl_1.setObjectName("lvl_1")
        self.let1_13 = QtWidgets.QLabel(self.lvl_1)
        self.let1_13.setGeometry(QtCore.QRect(330, 380, 51, 51))
        self.let1_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_13.setAutoFillBackground(False)
        self.let1_13.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_13.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_13.setObjectName("let1_13")
        self.let1_14 = QtWidgets.QLabel(self.lvl_1)
        self.let1_14.setGeometry(QtCore.QRect(930, 380, 51, 51))
        self.let1_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_14.setAutoFillBackground(False)
        self.let1_14.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_14.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_14.setObjectName("let1_14")
        self.yo_2 = QtWidgets.QLabel(self.lvl_1)
        self.yo_2.setGeometry(QtCore.QRect(190, 320, 51, 51))
        self.yo_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.yo_2.setAutoFillBackground(False)
        self.yo_2.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.yo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.yo_2.setObjectName("yo_2")
        self.let2_12 = QtWidgets.QLabel(self.lvl_1)
        self.let2_12.setGeometry(QtCore.QRect(780, 440, 51, 51))
        self.let2_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_12.setAutoFillBackground(False)
        self.let2_12.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_12.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_12.setObjectName("let2_12")
        self.let2_13 = QtWidgets.QLabel(self.lvl_1)
        self.let2_13.setGeometry(QtCore.QRect(540, 440, 51, 51))
        self.let2_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_13.setAutoFillBackground(False)
        self.let2_13.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_13.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_13.setObjectName("let2_13")
        self.let3_11 = QtWidgets.QLabel(self.lvl_1)
        self.let3_11.setGeometry(QtCore.QRect(520, 500, 51, 51))
        self.let3_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_11.setAutoFillBackground(False)
        self.let3_11.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_11.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_11.setObjectName("let3_11")
        self.n1_2 = QtWidgets.QLabel(self.lvl_1)
        self.n1_2.setGeometry(QtCore.QRect(250, 320, 51, 51))
        self.n1_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n1_2.setAutoFillBackground(False)
        self.n1_2.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(0, 0, 0);\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.n1_2.setObjectName("n1_2")
        self.shift_l_2 = QtWidgets.QLabel(self.lvl_1)
        self.shift_l_2.setGeometry(QtCore.QRect(940, 500, 141, 51))
        self.shift_l_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.shift_l_2.setAutoFillBackground(False)
        self.shift_l_2.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.shift_l_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shift_l_2.setIndent(10)
        self.shift_l_2.setObjectName("shift_l_2")
        self.let2_14 = QtWidgets.QLabel(self.lvl_1)
        self.let2_14.setGeometry(QtCore.QRect(660, 440, 51, 51))
        self.let2_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_14.setAutoFillBackground(False)
        self.let2_14.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_14.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_14.setObjectName("let2_14")
        self.enter_2 = QtWidgets.QLabel(self.lvl_1)
        self.enter_2.setGeometry(QtCore.QRect(960, 440, 121, 51))
        self.enter_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.enter_2.setAutoFillBackground(False)
        self.enter_2.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.enter_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.enter_2.setIndent(10)
        self.enter_2.setObjectName("enter_2")
        self.n9_2 = QtWidgets.QLabel(self.lvl_1)
        self.n9_2.setGeometry(QtCore.QRect(730, 320, 51, 51))
        self.n9_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n9_2.setAutoFillBackground(False)
        self.n9_2.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n9_2.setAlignment(QtCore.Qt.AlignCenter)
        self.n9_2.setObjectName("n9_2")
        self.text_1 = QtWidgets.QLabel(self.lvl_1)
        self.text_1.setGeometry(QtCore.QRect(180, 180, 911, 71))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.text_1.setFont(font)
        self.text_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_1.setObjectName("text_1")
        self.let2_15 = QtWidgets.QLabel(self.lvl_1)
        self.let2_15.setGeometry(QtCore.QRect(420, 440, 51, 51))
        self.let2_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_15.setAutoFillBackground(False)
        self.let2_15.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_15.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_15.setObjectName("let2_15")
        self.shift_r_2 = QtWidgets.QLabel(self.lvl_1)
        self.shift_r_2.setGeometry(QtCore.QRect(190, 500, 141, 51))
        self.shift_r_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.shift_r_2.setAutoFillBackground(False)
        self.shift_r_2.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.shift_r_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shift_r_2.setIndent(10)
        self.shift_r_2.setObjectName("shift_r_2")
        self.n7_2 = QtWidgets.QLabel(self.lvl_1)
        self.n7_2.setGeometry(QtCore.QRect(610, 320, 51, 51))
        self.n7_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n7_2.setAutoFillBackground(False)
        self.n7_2.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n7_2.setAlignment(QtCore.Qt.AlignCenter)
        self.n7_2.setObjectName("n7_2")
        self.eq_2 = QtWidgets.QLabel(self.lvl_1)
        self.eq_2.setGeometry(QtCore.QRect(910, 320, 51, 51))
        self.eq_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.eq_2.setAutoFillBackground(False)
        self.eq_2.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.eq_2.setAlignment(QtCore.Qt.AlignCenter)
        self.eq_2.setObjectName("eq_2")
        self.let3_12 = QtWidgets.QLabel(self.lvl_1)
        self.let3_12.setGeometry(QtCore.QRect(400, 500, 51, 51))
        self.let3_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_12.setAutoFillBackground(False)
        self.let3_12.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_12.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_12.setObjectName("let3_12")
        self.let1_15 = QtWidgets.QLabel(self.lvl_1)
        self.let1_15.setGeometry(QtCore.QRect(630, 380, 51, 51))
        self.let1_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_15.setAutoFillBackground(False)
        self.let1_15.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_15.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_15.setObjectName("let1_15")
        self.let2_16 = QtWidgets.QLabel(self.lvl_1)
        self.let2_16.setGeometry(QtCore.QRect(360, 440, 51, 51))
        self.let2_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_16.setAutoFillBackground(False)
        self.let2_16.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_16.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_16.setObjectName("let2_16")
        self.ctrl_l_2 = QtWidgets.QLabel(self.lvl_1)
        self.ctrl_l_2.setGeometry(QtCore.QRect(190, 560, 71, 51))
        self.ctrl_l_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ctrl_l_2.setAutoFillBackground(False)
        self.ctrl_l_2.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.ctrl_l_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ctrl_l_2.setObjectName("ctrl_l_2")
        self.backspace_2 = QtWidgets.QLabel(self.lvl_1)
        self.backspace_2.setGeometry(QtCore.QRect(970, 320, 111, 51))
        self.backspace_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.backspace_2.setAutoFillBackground(False)
        self.backspace_2.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.backspace_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.backspace_2.setIndent(10)
        self.backspace_2.setObjectName("backspace_2")
        self.let1_16 = QtWidgets.QLabel(self.lvl_1)
        self.let1_16.setGeometry(QtCore.QRect(690, 380, 51, 51))
        self.let1_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_16.setAutoFillBackground(False)
        self.let1_16.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_16.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_16.setObjectName("let1_16")
        self.let1_17 = QtWidgets.QLabel(self.lvl_1)
        self.let1_17.setGeometry(QtCore.QRect(750, 380, 51, 51))
        self.let1_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_17.setAutoFillBackground(False)
        self.let1_17.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_17.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_17.setObjectName("let1_17")
        self.let1_18 = QtWidgets.QLabel(self.lvl_1)
        self.let1_18.setGeometry(QtCore.QRect(450, 380, 51, 51))
        self.let1_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_18.setAutoFillBackground(False)
        self.let1_18.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_18.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_18.setObjectName("let1_18")
        self.n2_2 = QtWidgets.QLabel(self.lvl_1)
        self.n2_2.setGeometry(QtCore.QRect(310, 320, 51, 51))
        self.n2_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n2_2.setAutoFillBackground(False)
        self.n2_2.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.n2_2.setObjectName("n2_2")
        self.win_l_2 = QtWidgets.QLabel(self.lvl_1)
        self.win_l_2.setGeometry(QtCore.QRect(270, 560, 61, 51))
        self.win_l_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.win_l_2.setAutoFillBackground(False)
        self.win_l_2.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.win_l_2.setAlignment(QtCore.Qt.AlignCenter)
        self.win_l_2.setObjectName("win_l_2")
        self.slash_2 = QtWidgets.QLabel(self.lvl_1)
        self.slash_2.setGeometry(QtCore.QRect(990, 380, 91, 51))
        self.slash_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.slash_2.setAutoFillBackground(False)
        self.slash_2.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.slash_2.setAlignment(QtCore.Qt.AlignCenter)
        self.slash_2.setObjectName("slash_2")
        self.let3_13 = QtWidgets.QLabel(self.lvl_1)
        self.let3_13.setGeometry(QtCore.QRect(460, 500, 51, 51))
        self.let3_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_13.setAutoFillBackground(False)
        self.let3_13.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_13.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_13.setObjectName("let3_13")
        self.let1_19 = QtWidgets.QLabel(self.lvl_1)
        self.let1_19.setGeometry(QtCore.QRect(570, 380, 51, 51))
        self.let1_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_19.setAutoFillBackground(False)
        self.let1_19.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_19.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_19.setObjectName("let1_19")
        self.let2_17 = QtWidgets.QLabel(self.lvl_1)
        self.let2_17.setGeometry(QtCore.QRect(480, 440, 51, 51))
        self.let2_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_17.setAutoFillBackground(False)
        self.let2_17.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_17.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_17.setObjectName("let2_17")
        self.let3_14 = QtWidgets.QLabel(self.lvl_1)
        self.let3_14.setGeometry(QtCore.QRect(700, 500, 51, 51))
        self.let3_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_14.setAutoFillBackground(False)
        self.let3_14.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_14.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_14.setObjectName("let3_14")
        self.n4_2 = QtWidgets.QLabel(self.lvl_1)
        self.n4_2.setGeometry(QtCore.QRect(430, 320, 51, 51))
        self.n4_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n4_2.setAutoFillBackground(False)
        self.n4_2.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.n4_2.setObjectName("n4_2")
        self.space_2 = QtWidgets.QLabel(self.lvl_1)
        self.space_2.setGeometry(QtCore.QRect(410, 560, 391, 51))
        self.space_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.space_2.setAutoFillBackground(False)
        self.space_2.setStyleSheet("background-color: rgb(175, 175, 225);\n"
"font: 10pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.space_2.setText("")
        self.space_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.space_2.setObjectName("space_2")
        self.let3_15 = QtWidgets.QLabel(self.lvl_1)
        self.let3_15.setGeometry(QtCore.QRect(820, 500, 51, 51))
        self.let3_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_15.setAutoFillBackground(False)
        self.let3_15.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_15.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_15.setObjectName("let3_15")
        self.let2_18 = QtWidgets.QLabel(self.lvl_1)
        self.let2_18.setGeometry(QtCore.QRect(720, 440, 51, 51))
        self.let2_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_18.setAutoFillBackground(False)
        self.let2_18.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_18.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_18.setObjectName("let2_18")
        self.n3_2 = QtWidgets.QLabel(self.lvl_1)
        self.n3_2.setGeometry(QtCore.QRect(370, 320, 51, 51))
        self.n3_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n3_2.setAutoFillBackground(False)
        self.n3_2.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.n3_2.setObjectName("n3_2")
        self.let1_20 = QtWidgets.QLabel(self.lvl_1)
        self.let1_20.setGeometry(QtCore.QRect(810, 380, 51, 51))
        self.let1_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_20.setAutoFillBackground(False)
        self.let1_20.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_20.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_20.setObjectName("let1_20")
        self.let3_16 = QtWidgets.QLabel(self.lvl_1)
        self.let3_16.setGeometry(QtCore.QRect(340, 500, 51, 51))
        self.let3_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_16.setAutoFillBackground(False)
        self.let3_16.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_16.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_16.setObjectName("let3_16")
        self.let2_19 = QtWidgets.QLabel(self.lvl_1)
        self.let2_19.setGeometry(QtCore.QRect(840, 440, 51, 51))
        self.let2_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_19.setAutoFillBackground(False)
        self.let2_19.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_19.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_19.setObjectName("let2_19")
        self.let1_21 = QtWidgets.QLabel(self.lvl_1)
        self.let1_21.setGeometry(QtCore.QRect(870, 380, 51, 51))
        self.let1_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_21.setAutoFillBackground(False)
        self.let1_21.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_21.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_21.setObjectName("let1_21")
        self.let1_22 = QtWidgets.QLabel(self.lvl_1)
        self.let1_22.setGeometry(QtCore.QRect(270, 380, 51, 51))
        self.let1_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_22.setAutoFillBackground(False)
        self.let1_22.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_22.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_22.setObjectName("let1_22")
        self.win_r_2 = QtWidgets.QLabel(self.lvl_1)
        self.win_r_2.setGeometry(QtCore.QRect(880, 560, 61, 51))
        self.win_r_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.win_r_2.setAutoFillBackground(False)
        self.win_r_2.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.win_r_2.setAlignment(QtCore.Qt.AlignCenter)
        self.win_r_2.setObjectName("win_r_2")
        self.let3_17 = QtWidgets.QLabel(self.lvl_1)
        self.let3_17.setGeometry(QtCore.QRect(760, 500, 51, 51))
        self.let3_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_17.setAutoFillBackground(False)
        self.let3_17.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_17.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_17.setObjectName("let3_17")
        self.tab_2 = QtWidgets.QLabel(self.lvl_1)
        self.tab_2.setGeometry(QtCore.QRect(190, 380, 71, 51))
        self.tab_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_2.setAutoFillBackground(False)
        self.tab_2.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.tab_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tab_2.setObjectName("tab_2")
        self.dash_2 = QtWidgets.QLabel(self.lvl_1)
        self.dash_2.setGeometry(QtCore.QRect(850, 320, 51, 51))
        self.dash_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dash_2.setAutoFillBackground(False)
        self.dash_2.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.dash_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dash_2.setObjectName("dash_2")
        self.n8_2 = QtWidgets.QLabel(self.lvl_1)
        self.n8_2.setGeometry(QtCore.QRect(670, 320, 51, 51))
        self.n8_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n8_2.setAutoFillBackground(False)
        self.n8_2.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n8_2.setAlignment(QtCore.Qt.AlignCenter)
        self.n8_2.setObjectName("n8_2")
        self.let2_20 = QtWidgets.QLabel(self.lvl_1)
        self.let2_20.setGeometry(QtCore.QRect(300, 440, 51, 51))
        self.let2_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_20.setAutoFillBackground(False)
        self.let2_20.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_20.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_20.setObjectName("let2_20")
        self.let1_23 = QtWidgets.QLabel(self.lvl_1)
        self.let1_23.setGeometry(QtCore.QRect(510, 380, 51, 51))
        self.let1_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_23.setAutoFillBackground(False)
        self.let1_23.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_23.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_23.setObjectName("let1_23")
        self.caps_2 = QtWidgets.QLabel(self.lvl_1)
        self.caps_2.setGeometry(QtCore.QRect(190, 440, 101, 51))
        self.caps_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.caps_2.setAutoFillBackground(False)
        self.caps_2.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.caps_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.caps_2.setIndent(10)
        self.caps_2.setObjectName("caps_2")
        self.let2_21 = QtWidgets.QLabel(self.lvl_1)
        self.let2_21.setGeometry(QtCore.QRect(600, 440, 51, 51))
        self.let2_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_21.setAutoFillBackground(False)
        self.let2_21.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_21.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_21.setObjectName("let2_21")
        self.let3_18 = QtWidgets.QLabel(self.lvl_1)
        self.let3_18.setGeometry(QtCore.QRect(880, 500, 51, 51))
        self.let3_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_18.setAutoFillBackground(False)
        self.let3_18.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_18.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_18.setObjectName("let3_18")
        self.ctrl_r_2 = QtWidgets.QLabel(self.lvl_1)
        self.ctrl_r_2.setGeometry(QtCore.QRect(1020, 560, 61, 51))
        self.ctrl_r_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ctrl_r_2.setAutoFillBackground(False)
        self.ctrl_r_2.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.ctrl_r_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ctrl_r_2.setObjectName("ctrl_r_2")
        self.n6_2 = QtWidgets.QLabel(self.lvl_1)
        self.n6_2.setGeometry(QtCore.QRect(550, 320, 51, 51))
        self.n6_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n6_2.setAutoFillBackground(False)
        self.n6_2.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n6_2.setAlignment(QtCore.Qt.AlignCenter)
        self.n6_2.setObjectName("n6_2")
        self.let3_19 = QtWidgets.QLabel(self.lvl_1)
        self.let3_19.setGeometry(QtCore.QRect(580, 500, 51, 51))
        self.let3_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_19.setAutoFillBackground(False)
        self.let3_19.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_19.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_19.setObjectName("let3_19")
        self.let2_22 = QtWidgets.QLabel(self.lvl_1)
        self.let2_22.setGeometry(QtCore.QRect(900, 440, 51, 51))
        self.let2_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_22.setAutoFillBackground(False)
        self.let2_22.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_22.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_22.setObjectName("let2_22")
        self.n0_2 = QtWidgets.QLabel(self.lvl_1)
        self.n0_2.setGeometry(QtCore.QRect(790, 320, 51, 51))
        self.n0_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n0_2.setAutoFillBackground(False)
        self.n0_2.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n0_2.setAlignment(QtCore.Qt.AlignCenter)
        self.n0_2.setObjectName("n0_2")
        self.let3_20 = QtWidgets.QLabel(self.lvl_1)
        self.let3_20.setGeometry(QtCore.QRect(640, 500, 51, 51))
        self.let3_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_20.setAutoFillBackground(False)
        self.let3_20.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_20.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_20.setObjectName("let3_20")
        self.alt_r_2 = QtWidgets.QLabel(self.lvl_1)
        self.alt_r_2.setGeometry(QtCore.QRect(810, 560, 61, 51))
        self.alt_r_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.alt_r_2.setAutoFillBackground(False)
        self.alt_r_2.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.alt_r_2.setAlignment(QtCore.Qt.AlignCenter)
        self.alt_r_2.setObjectName("alt_r_2")
        self.bg_2 = QtWidgets.QLabel(self.lvl_1)
        self.bg_2.setGeometry(QtCore.QRect(170, 300, 931, 331))
        self.bg_2.setStyleSheet("background-color: rgb(153, 180, 209);\n"
"border-radius: 5px;")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")
        self.alt_l_2 = QtWidgets.QLabel(self.lvl_1)
        self.alt_l_2.setGeometry(QtCore.QRect(340, 560, 61, 51))
        self.alt_l_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.alt_l_2.setAutoFillBackground(False)
        self.alt_l_2.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.alt_l_2.setAlignment(QtCore.Qt.AlignCenter)
        self.alt_l_2.setObjectName("alt_l_2")
        self.n5_2 = QtWidgets.QLabel(self.lvl_1)
        self.n5_2.setGeometry(QtCore.QRect(490, 320, 51, 51))
        self.n5_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n5_2.setAutoFillBackground(False)
        self.n5_2.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n5_2.setAlignment(QtCore.Qt.AlignCenter)
        self.n5_2.setObjectName("n5_2")
        self.menu_2 = QtWidgets.QLabel(self.lvl_1)
        self.menu_2.setGeometry(QtCore.QRect(950, 560, 61, 51))
        self.menu_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menu_2.setAutoFillBackground(False)
        self.menu_2.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.menu_2.setAlignment(QtCore.Qt.AlignCenter)
        self.menu_2.setObjectName("menu_2")
        self.let1_24 = QtWidgets.QLabel(self.lvl_1)
        self.let1_24.setGeometry(QtCore.QRect(390, 380, 51, 51))
        self.let1_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_24.setAutoFillBackground(False)
        self.let1_24.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_24.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_24.setObjectName("let1_24")
        self.label = QtWidgets.QLabel(self.lvl_1)
        self.label.setGeometry(QtCore.QRect(-10, -10, 121, 41))
        self.label.setStyleSheet("background-color: rgba(188, 255, 199, 255);\n"
"background-color: rgb(156, 212, 165);\n"
"font: 10pt \"Montserrat Medium\";\n"
"border-radius: 10px;")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setIndent(5)
        self.label.setObjectName("label")

        self.label_4 = QtWidgets.QLabel(self.lvl_1)
        self.label_4.setGeometry(QtCore.QRect(590, 70, 91, 41))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"font: 15pt \"Roboto\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.button_start1 = QtWidgets.QPushButton(self.lvl_1)
        self.button_start1.setGeometry(QtCore.QRect(700, 75, 100, 30))
        self.button_start1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "border-radius: 10px;\n"
                                        "font: 15pt \"Roboto\";")
        self.button_start1.setObjectName("button_start")
        self.button_start1.clicked.connect(self.func_start1)

        self.switch1 = QtWidgets.QPushButton(self.lvl_1)
        self.switch1.setGeometry(QtCore.QRect(800, 75, 200, 30))
        self.switch1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border-radius: 10px;\n"
                                   "font: 10pt \"Roboto\";")
        self.switch1.setObjectName("switch1")
        self.switch1.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))

        self.temp1 = 0
        self.temp2 = 0

        self.timer1 = QtCore.QTimer()
        self.timer1.setInterval(1000)
        self.timer1.timeout.connect(self.displayTime1)

        self.timer2 = QtCore.QTimer()
        self.timer2.setInterval(1000)
        self.timer2.timeout.connect(self.displayTime2)

        self.bg_2.raise_()
        self.let1_13.raise_()
        self.let1_14.raise_()
        self.yo_2.raise_()
        self.let2_12.raise_()
        self.let2_13.raise_()
        self.let3_11.raise_()
        self.n1_2.raise_()
        self.shift_l_2.raise_()
        self.let2_14.raise_()
        self.enter_2.raise_()
        self.n9_2.raise_()
        self.text_1.raise_()
        self.let2_15.raise_()
        self.shift_r_2.raise_()
        self.n7_2.raise_()
        self.eq_2.raise_()
        self.let3_12.raise_()
        self.let1_15.raise_()
        self.let2_16.raise_()
        self.ctrl_l_2.raise_()
        self.backspace_2.raise_()
        self.let1_16.raise_()
        self.let1_17.raise_()
        self.let1_18.raise_()
        self.n2_2.raise_()
        self.win_l_2.raise_()
        self.slash_2.raise_()
        self.let3_13.raise_()
        self.let1_19.raise_()
        self.let2_17.raise_()
        self.let3_14.raise_()
        self.n4_2.raise_()
        self.space_2.raise_()
        self.let3_15.raise_()
        self.let2_18.raise_()
        self.n3_2.raise_()
        self.let1_20.raise_()
        self.let3_16.raise_()
        self.let2_19.raise_()
        self.let1_21.raise_()
        self.let1_22.raise_()
        self.win_r_2.raise_()
        self.let3_17.raise_()
        self.tab_2.raise_()
        self.dash_2.raise_()
        self.n8_2.raise_()
        self.let2_20.raise_()
        self.let1_23.raise_()
        self.caps_2.raise_()
        self.let2_21.raise_()
        self.let3_18.raise_()
        self.ctrl_r_2.raise_()
        self.n6_2.raise_()
        self.let3_19.raise_()
        self.let2_22.raise_()
        self.n0_2.raise_()
        self.let3_20.raise_()
        self.alt_r_2.raise_()
        self.alt_l_2.raise_()
        self.n5_2.raise_()
        self.menu_2.raise_()
        self.let1_24.raise_()
        self.label.raise_()

        self.label_4.raise_()
        self.button_start1.raise_()
        self.switch1.raise_()

        self.stackedWidget.addWidget(self.lvl_1)
        self.lvl_2 = QtWidgets.QWidget()
        self.lvl_2.setObjectName("lvl_2")
        self.shift_l = QtWidgets.QLabel(self.lvl_2)
        self.shift_l.setGeometry(QtCore.QRect(940, 500, 141, 51))
        self.shift_l.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.shift_l.setAutoFillBackground(False)
        self.shift_l.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.shift_l.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shift_l.setIndent(10)
        self.shift_l.setObjectName("shift_l")
        self.let1_12 = QtWidgets.QLabel(self.lvl_2)
        self.let1_12.setGeometry(QtCore.QRect(930, 380, 51, 51))
        self.let1_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_12.setAutoFillBackground(False)
        self.let1_12.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_12.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_12.setObjectName("let1_12")
        self.ctrl_l = QtWidgets.QLabel(self.lvl_2)
        self.ctrl_l.setGeometry(QtCore.QRect(190, 560, 71, 51))
        self.ctrl_l.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ctrl_l.setAutoFillBackground(False)
        self.ctrl_l.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.ctrl_l.setAlignment(QtCore.Qt.AlignCenter)
        self.ctrl_l.setObjectName("ctrl_l")
        self.let1_4 = QtWidgets.QLabel(self.lvl_2)
        self.let1_4.setGeometry(QtCore.QRect(450, 380, 51, 51))
        self.let1_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_4.setAutoFillBackground(False)
        self.let1_4.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_4.setObjectName("let1_4")
        self.n2 = QtWidgets.QLabel(self.lvl_2)
        self.n2.setGeometry(QtCore.QRect(310, 320, 51, 51))
        self.n2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n2.setAutoFillBackground(False)
        self.n2.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n2.setAlignment(QtCore.Qt.AlignCenter)
        self.n2.setObjectName("n2")
        self.n3 = QtWidgets.QLabel(self.lvl_2)
        self.n3.setGeometry(QtCore.QRect(370, 320, 51, 51))
        self.n3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n3.setAutoFillBackground(False)
        self.n3.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n3.setAlignment(QtCore.Qt.AlignCenter)
        self.n3.setObjectName("n3")
        self.let1_3 = QtWidgets.QLabel(self.lvl_2)
        self.let1_3.setGeometry(QtCore.QRect(390, 380, 51, 51))
        self.let1_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_3.setAutoFillBackground(False)
        self.let1_3.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_3.setObjectName("let1_3")
        self.dash = QtWidgets.QLabel(self.lvl_2)
        self.dash.setGeometry(QtCore.QRect(850, 320, 51, 51))
        self.dash.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dash.setAutoFillBackground(False)
        self.dash.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.dash.setAlignment(QtCore.Qt.AlignCenter)
        self.dash.setObjectName("dash")
        self.let1_5 = QtWidgets.QLabel(self.lvl_2)
        self.let1_5.setGeometry(QtCore.QRect(510, 380, 51, 51))
        self.let1_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_5.setAutoFillBackground(False)
        self.let1_5.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_5.setObjectName("let1_5")
        self.let3_7 = QtWidgets.QLabel(self.lvl_2)
        self.let3_7.setGeometry(QtCore.QRect(700, 500, 51, 51))
        self.let3_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_7.setAutoFillBackground(False)
        self.let3_7.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_7.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_7.setObjectName("let3_7")
        self.let3_9 = QtWidgets.QLabel(self.lvl_2)
        self.let3_9.setGeometry(QtCore.QRect(820, 500, 51, 51))
        self.let3_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_9.setAutoFillBackground(False)
        self.let3_9.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_9.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_9.setObjectName("let3_9")
        self.n9 = QtWidgets.QLabel(self.lvl_2)
        self.n9.setGeometry(QtCore.QRect(730, 320, 51, 51))
        self.n9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n9.setAutoFillBackground(False)
        self.n9.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n9.setAlignment(QtCore.Qt.AlignCenter)
        self.n9.setObjectName("n9")
        self.let3_8 = QtWidgets.QLabel(self.lvl_2)
        self.let3_8.setGeometry(QtCore.QRect(760, 500, 51, 51))
        self.let3_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_8.setAutoFillBackground(False)
        self.let3_8.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_8.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_8.setObjectName("let3_8")
        self.space = QtWidgets.QLabel(self.lvl_2)
        self.space.setGeometry(QtCore.QRect(410, 560, 391, 51))
        self.space.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.space.setAutoFillBackground(False)
        self.space.setStyleSheet("background-color: rgb(175, 175, 225);\n"
"font: 10pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.space.setText("")
        self.space.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.space.setObjectName("space")
        self.alt_l = QtWidgets.QLabel(self.lvl_2)
        self.alt_l.setGeometry(QtCore.QRect(340, 560, 61, 51))
        self.alt_l.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.alt_l.setAutoFillBackground(False)
        self.alt_l.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.alt_l.setAlignment(QtCore.Qt.AlignCenter)
        self.alt_l.setObjectName("alt_l")
        self.n5 = QtWidgets.QLabel(self.lvl_2)
        self.n5.setGeometry(QtCore.QRect(490, 320, 51, 51))
        self.n5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n5.setAutoFillBackground(False)
        self.n5.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n5.setAlignment(QtCore.Qt.AlignCenter)
        self.n5.setObjectName("n5")
        self.let3_6 = QtWidgets.QLabel(self.lvl_2)
        self.let3_6.setGeometry(QtCore.QRect(640, 500, 51, 51))
        self.let3_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_6.setAutoFillBackground(False)
        self.let3_6.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_6.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_6.setObjectName("let3_6")
        self.slash = QtWidgets.QLabel(self.lvl_2)
        self.slash.setGeometry(QtCore.QRect(990, 380, 91, 51))
        self.slash.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.slash.setAutoFillBackground(False)
        self.slash.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.slash.setAlignment(QtCore.Qt.AlignCenter)
        self.slash.setObjectName("slash")
        self.n4 = QtWidgets.QLabel(self.lvl_2)
        self.n4.setGeometry(QtCore.QRect(430, 320, 51, 51))
        self.n4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n4.setAutoFillBackground(False)
        self.n4.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n4.setAlignment(QtCore.Qt.AlignCenter)
        self.n4.setObjectName("n4")
        self.let1_10 = QtWidgets.QLabel(self.lvl_2)
        self.let1_10.setGeometry(QtCore.QRect(810, 380, 51, 51))
        self.let1_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_10.setAutoFillBackground(False)
        self.let1_10.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_10.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_10.setObjectName("let1_10")
        self.let2_2 = QtWidgets.QLabel(self.lvl_2)
        self.let2_2.setGeometry(QtCore.QRect(360, 440, 51, 51))
        self.let2_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_2.setAutoFillBackground(False)
        self.let2_2.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_2.setObjectName("let2_2")
        self.let3_5 = QtWidgets.QLabel(self.lvl_2)
        self.let3_5.setGeometry(QtCore.QRect(580, 500, 51, 51))
        self.let3_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_5.setAutoFillBackground(False)
        self.let3_5.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_5.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_5.setObjectName("let3_5")
        self.yo = QtWidgets.QLabel(self.lvl_2)
        self.yo.setGeometry(QtCore.QRect(190, 320, 51, 51))
        self.yo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.yo.setAutoFillBackground(False)
        self.yo.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.yo.setAlignment(QtCore.Qt.AlignCenter)
        self.yo.setObjectName("yo")
        self.n1 = QtWidgets.QLabel(self.lvl_2)
        self.n1.setGeometry(QtCore.QRect(250, 320, 51, 51))
        self.n1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n1.setAutoFillBackground(False)
        self.n1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(0, 0, 0);\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n1.setAlignment(QtCore.Qt.AlignCenter)
        self.n1.setObjectName("n1")
        self.let3_2 = QtWidgets.QLabel(self.lvl_2)
        self.let3_2.setGeometry(QtCore.QRect(400, 500, 51, 51))
        self.let3_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_2.setAutoFillBackground(False)
        self.let3_2.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_2.setObjectName("let3_2")
        self.caps = QtWidgets.QLabel(self.lvl_2)
        self.caps.setGeometry(QtCore.QRect(190, 440, 101, 51))
        self.caps.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.caps.setAutoFillBackground(False)
        self.caps.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.caps.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.caps.setIndent(10)
        self.caps.setObjectName("caps")
        self.let3_10 = QtWidgets.QLabel(self.lvl_2)
        self.let3_10.setGeometry(QtCore.QRect(880, 500, 51, 51))
        self.let3_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_10.setAutoFillBackground(False)
        self.let3_10.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_10.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_10.setObjectName("let3_10")
        self.n0 = QtWidgets.QLabel(self.lvl_2)
        self.n0.setGeometry(QtCore.QRect(790, 320, 51, 51))
        self.n0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n0.setAutoFillBackground(False)
        self.n0.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n0.setAlignment(QtCore.Qt.AlignCenter)
        self.n0.setObjectName("n0")
        self.let2_7 = QtWidgets.QLabel(self.lvl_2)
        self.let2_7.setGeometry(QtCore.QRect(660, 440, 51, 51))
        self.let2_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_7.setAutoFillBackground(False)
        self.let2_7.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_7.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_7.setObjectName("let2_7")
        self.ctrl_r = QtWidgets.QLabel(self.lvl_2)
        self.ctrl_r.setGeometry(QtCore.QRect(1020, 560, 61, 51))
        self.ctrl_r.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ctrl_r.setAutoFillBackground(False)
        self.ctrl_r.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.ctrl_r.setAlignment(QtCore.Qt.AlignCenter)
        self.ctrl_r.setObjectName("ctrl_r")
        self.let2_4 = QtWidgets.QLabel(self.lvl_2)
        self.let2_4.setGeometry(QtCore.QRect(480, 440, 51, 51))
        self.let2_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_4.setAutoFillBackground(False)
        self.let2_4.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_4.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_4.setObjectName("let2_4")
        self.win_r = QtWidgets.QLabel(self.lvl_2)
        self.win_r.setGeometry(QtCore.QRect(880, 560, 61, 51))
        self.win_r.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.win_r.setAutoFillBackground(False)
        self.win_r.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.win_r.setAlignment(QtCore.Qt.AlignCenter)
        self.win_r.setObjectName("win_r")
        self.enter = QtWidgets.QLabel(self.lvl_2)
        self.enter.setGeometry(QtCore.QRect(960, 440, 121, 51))
        self.enter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.enter.setAutoFillBackground(False)
        self.enter.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.enter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.enter.setIndent(10)
        self.enter.setObjectName("enter")
        self.let1_7 = QtWidgets.QLabel(self.lvl_2)
        self.let1_7.setGeometry(QtCore.QRect(630, 380, 51, 51))
        self.let1_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_7.setAutoFillBackground(False)
        self.let1_7.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_7.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_7.setObjectName("let1_7")
        self.let1_8 = QtWidgets.QLabel(self.lvl_2)
        self.let1_8.setGeometry(QtCore.QRect(690, 380, 51, 51))
        self.let1_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_8.setAutoFillBackground(False)
        self.let1_8.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_8.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_8.setObjectName("let1_8")
        self.let2_9 = QtWidgets.QLabel(self.lvl_2)
        self.let2_9.setGeometry(QtCore.QRect(780, 440, 51, 51))
        self.let2_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_9.setAutoFillBackground(False)
        self.let2_9.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_9.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_9.setObjectName("let2_9")
        self.backspace = QtWidgets.QLabel(self.lvl_2)
        self.backspace.setGeometry(QtCore.QRect(970, 320, 111, 51))
        self.backspace.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.backspace.setAutoFillBackground(False)
        self.backspace.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.backspace.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.backspace.setIndent(10)
        self.backspace.setObjectName("backspace")
        self.alt_r = QtWidgets.QLabel(self.lvl_2)
        self.alt_r.setGeometry(QtCore.QRect(810, 560, 61, 51))
        self.alt_r.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.alt_r.setAutoFillBackground(False)
        self.alt_r.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.alt_r.setAlignment(QtCore.Qt.AlignCenter)
        self.alt_r.setObjectName("alt_r")
        self.let1_2 = QtWidgets.QLabel(self.lvl_2)
        self.let1_2.setGeometry(QtCore.QRect(330, 380, 51, 51))
        self.let1_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_2.setAutoFillBackground(False)
        self.let1_2.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_2.setObjectName("let1_2")
        self.let3_1 = QtWidgets.QLabel(self.lvl_2)
        self.let3_1.setGeometry(QtCore.QRect(340, 500, 51, 51))
        self.let3_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_1.setAutoFillBackground(False)
        self.let3_1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_1.setObjectName("let3_1")
        self.let2_5 = QtWidgets.QLabel(self.lvl_2)
        self.let2_5.setGeometry(QtCore.QRect(540, 440, 51, 51))
        self.let2_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_5.setAutoFillBackground(False)
        self.let2_5.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_5.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_5.setObjectName("let2_5")
        self.let1_6 = QtWidgets.QLabel(self.lvl_2)
        self.let1_6.setGeometry(QtCore.QRect(570, 380, 51, 51))
        self.let1_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_6.setAutoFillBackground(False)
        self.let1_6.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_6.setObjectName("let1_6")
        self.let2_3 = QtWidgets.QLabel(self.lvl_2)
        self.let2_3.setGeometry(QtCore.QRect(420, 440, 51, 51))
        self.let2_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_3.setAutoFillBackground(False)
        self.let2_3.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_3.setObjectName("let2_3")
        self.let2_10 = QtWidgets.QLabel(self.lvl_2)
        self.let2_10.setGeometry(QtCore.QRect(840, 440, 51, 51))
        self.let2_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_10.setAutoFillBackground(False)
        self.let2_10.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_10.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_10.setObjectName("let2_10")
        self.let1_11 = QtWidgets.QLabel(self.lvl_2)
        self.let1_11.setGeometry(QtCore.QRect(870, 380, 51, 51))
        self.let1_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_11.setAutoFillBackground(False)
        self.let1_11.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_11.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_11.setObjectName("let1_11")
        self.let1_1 = QtWidgets.QLabel(self.lvl_2)
        self.let1_1.setGeometry(QtCore.QRect(270, 380, 51, 51))
        self.let1_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_1.setAutoFillBackground(False)
        self.let1_1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_1.setObjectName("let1_1")
        self.let2_6 = QtWidgets.QLabel(self.lvl_2)
        self.let2_6.setGeometry(QtCore.QRect(600, 440, 51, 51))
        self.let2_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_6.setAutoFillBackground(False)
        self.let2_6.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_6.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_6.setObjectName("let2_6")
        self.bg = QtWidgets.QLabel(self.lvl_2)
        self.bg.setGeometry(QtCore.QRect(170, 300, 931, 331))
        self.bg.setStyleSheet("background-color: rgb(153, 180, 209);\n"
"border-radius: 5px;")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.let2_11 = QtWidgets.QLabel(self.lvl_2)
        self.let2_11.setGeometry(QtCore.QRect(900, 440, 51, 51))
        self.let2_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_11.setAutoFillBackground(False)
        self.let2_11.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_11.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_11.setObjectName("let2_11")
        self.let3_4 = QtWidgets.QLabel(self.lvl_2)
        self.let3_4.setGeometry(QtCore.QRect(520, 500, 51, 51))
        self.let3_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_4.setAutoFillBackground(False)
        self.let3_4.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_4.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_4.setObjectName("let3_4")
        self.shift_r = QtWidgets.QLabel(self.lvl_2)
        self.shift_r.setGeometry(QtCore.QRect(190, 500, 141, 51))
        self.shift_r.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.shift_r.setAutoFillBackground(False)
        self.shift_r.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.shift_r.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shift_r.setIndent(10)
        self.shift_r.setObjectName("shift_r")
        self.n7 = QtWidgets.QLabel(self.lvl_2)
        self.n7.setGeometry(QtCore.QRect(610, 320, 51, 51))
        self.n7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n7.setAutoFillBackground(False)
        self.n7.setStyleSheet("background-color: rgb(223, 173, 226);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n7.setAlignment(QtCore.Qt.AlignCenter)
        self.n7.setObjectName("n7")
        self.win_l = QtWidgets.QLabel(self.lvl_2)
        self.win_l.setGeometry(QtCore.QRect(270, 560, 61, 51))
        self.win_l.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.win_l.setAutoFillBackground(False)
        self.win_l.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.win_l.setAlignment(QtCore.Qt.AlignCenter)
        self.win_l.setObjectName("win_l")
        self.let2_8 = QtWidgets.QLabel(self.lvl_2)
        self.let2_8.setGeometry(QtCore.QRect(720, 440, 51, 51))
        self.let2_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_8.setAutoFillBackground(False)
        self.let2_8.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_8.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_8.setObjectName("let2_8")
        self.let1_9 = QtWidgets.QLabel(self.lvl_2)
        self.let1_9.setGeometry(QtCore.QRect(750, 380, 51, 51))
        self.let1_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let1_9.setAutoFillBackground(False)
        self.let1_9.setStyleSheet("background-color: rgb(226, 224, 173);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let1_9.setAlignment(QtCore.Qt.AlignCenter)
        self.let1_9.setObjectName("let1_9")
        self.eq = QtWidgets.QLabel(self.lvl_2)
        self.eq.setGeometry(QtCore.QRect(910, 320, 51, 51))
        self.eq.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.eq.setAutoFillBackground(False)
        self.eq.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.eq.setAlignment(QtCore.Qt.AlignCenter)
        self.eq.setObjectName("eq")
        self.let2_1 = QtWidgets.QLabel(self.lvl_2)
        self.let2_1.setGeometry(QtCore.QRect(300, 440, 51, 51))
        self.let2_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let2_1.setAutoFillBackground(False)
        self.let2_1.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.let2_1.setObjectName("let2_1")
        self.n8 = QtWidgets.QLabel(self.lvl_2)
        self.n8.setGeometry(QtCore.QRect(670, 320, 51, 51))
        self.n8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n8.setAutoFillBackground(False)
        self.n8.setStyleSheet("background-color: rgb(225, 175, 174);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n8.setAlignment(QtCore.Qt.AlignCenter)
        self.n8.setObjectName("n8")
        self.n6 = QtWidgets.QLabel(self.lvl_2)
        self.n6.setGeometry(QtCore.QRect(550, 320, 51, 51))
        self.n6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.n6.setAutoFillBackground(False)
        self.n6.setStyleSheet("background-color: rgb(173, 226, 222);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.n6.setAlignment(QtCore.Qt.AlignCenter)
        self.n6.setObjectName("n6")
        self.let3_3 = QtWidgets.QLabel(self.lvl_2)
        self.let3_3.setGeometry(QtCore.QRect(460, 500, 51, 51))
        self.let3_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.let3_3.setAutoFillBackground(False)
        self.let3_3.setStyleSheet("background-color: rgb(173, 227, 176);\n"
"font: 15pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.let3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.let3_3.setObjectName("let3_3")
        self.menu = QtWidgets.QLabel(self.lvl_2)
        self.menu.setGeometry(QtCore.QRect(950, 560, 61, 51))
        self.menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menu.setAutoFillBackground(False)
        self.menu.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.menu.setAlignment(QtCore.Qt.AlignCenter)
        self.menu.setObjectName("menu")
        self.tab = QtWidgets.QLabel(self.lvl_2)
        self.tab.setGeometry(QtCore.QRect(190, 380, 71, 51))
        self.tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab.setAutoFillBackground(False)
        self.tab.setStyleSheet("background-color: rgb(215, 215, 215);\n"
"color: rgb(50, 50, 50);\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 5px;\n"
"border: 1px solid rgb(100, 100, 100);")
        self.tab.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tab.setObjectName("tab")
        self.text_2 = QtWidgets.QLabel(self.lvl_2)
        self.text_2.setGeometry(QtCore.QRect(180, 180, 911, 71))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.text_2.setFont(font)
        self.text_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_2.setObjectName("text_2")
        self.label_2 = QtWidgets.QLabel(self.lvl_2)
        self.label_2.setGeometry(QtCore.QRect(-10, -10, 121, 41))
        self.label_2.setStyleSheet("background-color: rgba(188, 255, 199, 255);\n"
"background-color: rgb(156, 212, 165);\n"
"font: 10pt \"Montserrat Medium\";\n"
"border-radius: 10px;")
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setIndent(5)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.lvl_2)
        self.label_3.setGeometry(QtCore.QRect(590, 70, 91, 41))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"font: 15pt \"Roboto\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.button_start2 = QtWidgets.QPushButton(self.lvl_2)
        self.button_start2.setGeometry(QtCore.QRect(700, 75, 100, 30))
        self.button_start2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                         "border-radius: 10px;\n"
                                         "font: 15pt \"Roboto\";")
        self.button_start2.setObjectName("button_start")
        self.button_start2.clicked.connect(self.func_start2)

        self.switch2 = QtWidgets.QPushButton(self.lvl_2)
        self.switch2.setGeometry(QtCore.QRect(800, 75, 200, 30))
        self.switch2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                         "border-radius: 10px;\n"
                                         "font: 10pt \"Roboto\";")
        self.switch2.setObjectName("switch2")
        self.switch2.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))

        self.button_start2.raise_()
        self.switch2.raise_()
        self.bg.raise_()
        self.shift_l.raise_()
        self.let1_12.raise_()
        self.ctrl_l.raise_()
        self.let1_4.raise_()
        self.n2.raise_()
        self.n3.raise_()
        self.let1_3.raise_()
        self.dash.raise_()
        self.let1_5.raise_()
        self.let3_7.raise_()
        self.let3_9.raise_()
        self.n9.raise_()
        self.let3_8.raise_()
        self.space.raise_()
        self.alt_l.raise_()
        self.n5.raise_()
        self.let3_6.raise_()
        self.slash.raise_()
        self.n4.raise_()
        self.let1_10.raise_()
        self.let2_2.raise_()
        self.let3_5.raise_()
        self.yo.raise_()
        self.n1.raise_()
        self.let3_2.raise_()
        self.caps.raise_()
        self.let3_10.raise_()
        self.n0.raise_()
        self.let2_7.raise_()
        self.ctrl_r.raise_()
        self.let2_4.raise_()
        self.win_r.raise_()
        self.enter.raise_()
        self.let1_7.raise_()
        self.let1_8.raise_()
        self.let2_9.raise_()
        self.backspace.raise_()
        self.alt_r.raise_()
        self.let1_2.raise_()
        self.let3_1.raise_()
        self.let2_5.raise_()
        self.let1_6.raise_()
        self.let2_3.raise_()
        self.let2_10.raise_()
        self.let1_11.raise_()
        self.let1_1.raise_()
        self.let2_6.raise_()
        self.let2_11.raise_()
        self.let3_4.raise_()
        self.shift_r.raise_()
        self.n7.raise_()
        self.win_l.raise_()
        self.let2_8.raise_()
        self.let1_9.raise_()
        self.eq.raise_()
        self.let2_1.raise_()
        self.n8.raise_()
        self.n6.raise_()
        self.let3_3.raise_()
        self.menu.raise_()
        self.tab.raise_()
        self.text_2.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.stackedWidget.addWidget(self.lvl_2)
        Fast_type.setCentralWidget(self.centralwidget)

        self.retranslateUi(Fast_type)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Fast_type)

    def retranslateUi(self, Fast_type):
        _translate = QtCore.QCoreApplication.translate
        Fast_type.setWindowTitle(_translate("Fast_type", "Fast type"))
        self.let1_13.setText(_translate("Fast_type", "ц"))
        self.let1_14.setText(_translate("Fast_type", "ъ"))
        self.yo_2.setText(_translate("Fast_type", "ё"))
        self.let2_12.setText(_translate("Fast_type", "д"))
        self.let2_13.setText(_translate("Fast_type", "п"))
        self.let3_11.setText(_translate("Fast_type", "м"))
        self.n1_2.setText(_translate("Fast_type", "1"))
        self.shift_l_2.setText(_translate("Fast_type", "Shift"))
        self.let2_14.setText(_translate("Fast_type", "о"))
        self.enter_2.setText(_translate("Fast_type", "Enter"))
        self.n9_2.setText(_translate("Fast_type", "9"))
        self.text_1.setText(_translate("Fast_type", "Просто текст"))
        self.let2_15.setText(_translate("Fast_type", "в"))
        self.shift_r_2.setText(_translate("Fast_type", "Shift"))
        self.n7_2.setText(_translate("Fast_type", "7"))
        self.eq_2.setText(_translate("Fast_type", "="))
        self.let3_12.setText(_translate("Fast_type", "ч"))
        self.let1_15.setText(_translate("Fast_type", "г"))
        self.let2_16.setText(_translate("Fast_type", "ы"))
        self.ctrl_l_2.setText(_translate("Fast_type", "Ctrl"))
        self.backspace_2.setText(_translate("Fast_type", "Backspace"))
        self.let1_16.setText(_translate("Fast_type", "ш"))
        self.let1_17.setText(_translate("Fast_type", "щ"))
        self.let1_18.setText(_translate("Fast_type", "к"))
        self.n2_2.setText(_translate("Fast_type", "2"))
        self.win_l_2.setText(_translate("Fast_type", "Win"))
        self.slash_2.setText(_translate("Fast_type", "\\"))
        self.let3_13.setText(_translate("Fast_type", "с"))
        self.let1_19.setText(_translate("Fast_type", "н"))
        self.let2_17.setText(_translate("Fast_type", "а"))
        self.let3_14.setText(_translate("Fast_type", "ь"))
        self.n4_2.setText(_translate("Fast_type", "4"))
        self.let3_15.setText(_translate("Fast_type", "ю"))
        self.let2_18.setText(_translate("Fast_type", "л"))
        self.n3_2.setText(_translate("Fast_type", "3"))
        self.let1_20.setText(_translate("Fast_type", "з"))
        self.let3_16.setText(_translate("Fast_type", "я"))
        self.let2_19.setText(_translate("Fast_type", "ж"))
        self.let1_21.setText(_translate("Fast_type", "х"))
        self.let1_22.setText(_translate("Fast_type", "й"))
        self.win_r_2.setText(_translate("Fast_type", "Win"))
        self.let3_17.setText(_translate("Fast_type", "б"))
        self.tab_2.setText(_translate("Fast_type", "Tab"))
        self.dash_2.setText(_translate("Fast_type", "-"))
        self.n8_2.setText(_translate("Fast_type", "8"))
        self.let2_20.setText(_translate("Fast_type", "ф"))
        self.let1_23.setText(_translate("Fast_type", "е"))
        self.caps_2.setText(_translate("Fast_type", "Caps Lock"))
        self.let2_21.setText(_translate("Fast_type", "р"))
        self.let3_18.setText(_translate("Fast_type", "."))
        self.ctrl_r_2.setText(_translate("Fast_type", "Ctrl"))
        self.n6_2.setText(_translate("Fast_type", "6"))
        self.let3_19.setText(_translate("Fast_type", "и"))
        self.let2_22.setText(_translate("Fast_type", "э"))
        self.n0_2.setText(_translate("Fast_type", "0"))
        self.let3_20.setText(_translate("Fast_type", "т"))
        self.alt_r_2.setText(_translate("Fast_type", "Alt"))
        self.alt_l_2.setText(_translate("Fast_type", "Alt"))
        self.n5_2.setText(_translate("Fast_type", "5"))
        self.menu_2.setText(_translate("Fast_type", "Menu"))
        self.let1_24.setText(_translate("Fast_type", "у"))
        self.label.setText(_translate("Fast_type", "Уровень 1"))

        self.label_4.setText(_translate("Fast_type", "00:00"))
        self.button_start1.setText(_translate("Fast_type", "Старт"))
        self.button_start2.setText(_translate("Fast_type", "Старт"))
        self.switch1.setText(_translate("Fast_type", "Сменить страницу"))
        self.switch2.setText(_translate("Fast_type", "Сменить страницу"))

        self.shift_l.setText(_translate("Fast_type", "Shift"))
        self.let1_12.setText(_translate("Fast_type", "ъ"))
        self.ctrl_l.setText(_translate("Fast_type", "Ctrl"))
        self.let1_4.setText(_translate("Fast_type", "к"))
        self.n2.setText(_translate("Fast_type", "2"))
        self.n3.setText(_translate("Fast_type", "3"))
        self.let1_3.setText(_translate("Fast_type", "у"))
        self.dash.setText(_translate("Fast_type", "-"))
        self.let1_5.setText(_translate("Fast_type", "е"))
        self.let3_7.setText(_translate("Fast_type", "ь"))
        self.let3_9.setText(_translate("Fast_type", "ю"))
        self.n9.setText(_translate("Fast_type", "9"))
        self.let3_8.setText(_translate("Fast_type", "б"))
        self.alt_l.setText(_translate("Fast_type", "Alt"))
        self.n5.setText(_translate("Fast_type", "5"))
        self.let3_6.setText(_translate("Fast_type", "т"))
        self.slash.setText(_translate("Fast_type", "\\"))
        self.n4.setText(_translate("Fast_type", "4"))
        self.let1_10.setText(_translate("Fast_type", "з"))
        self.let2_2.setText(_translate("Fast_type", "ы"))
        self.let3_5.setText(_translate("Fast_type", "и"))
        self.yo.setText(_translate("Fast_type", "ё"))
        self.n1.setText(_translate("Fast_type", "1"))
        self.let3_2.setText(_translate("Fast_type", "ч"))
        self.caps.setText(_translate("Fast_type", "Caps Lock"))
        self.let3_10.setText(_translate("Fast_type", "."))
        self.n0.setText(_translate("Fast_type", "0"))
        self.let2_7.setText(_translate("Fast_type", "о"))
        self.ctrl_r.setText(_translate("Fast_type", "Ctrl"))
        self.let2_4.setText(_translate("Fast_type", "а"))
        self.win_r.setText(_translate("Fast_type", "Win"))
        self.enter.setText(_translate("Fast_type", "Enter"))
        self.let1_7.setText(_translate("Fast_type", "г"))
        self.let1_8.setText(_translate("Fast_type", "ш"))
        self.let2_9.setText(_translate("Fast_type", "д"))
        self.backspace.setText(_translate("Fast_type", "Backspace"))
        self.alt_r.setText(_translate("Fast_type", "Alt"))
        self.let1_2.setText(_translate("Fast_type", "ц"))
        self.let3_1.setText(_translate("Fast_type", "я"))
        self.let2_5.setText(_translate("Fast_type", "п"))
        self.let1_6.setText(_translate("Fast_type", "н"))
        self.let2_3.setText(_translate("Fast_type", "в"))
        self.let2_10.setText(_translate("Fast_type", "ж"))
        self.let1_11.setText(_translate("Fast_type", "х"))
        self.let1_1.setText(_translate("Fast_type", "й"))
        self.let2_6.setText(_translate("Fast_type", "р"))
        self.let2_11.setText(_translate("Fast_type", "э"))
        self.let3_4.setText(_translate("Fast_type", "м"))
        self.shift_r.setText(_translate("Fast_type", "Shift"))
        self.n7.setText(_translate("Fast_type", "7"))
        self.win_l.setText(_translate("Fast_type", "Win"))
        self.let2_8.setText(_translate("Fast_type", "л"))
        self.let1_9.setText(_translate("Fast_type", "щ"))
        self.eq.setText(_translate("Fast_type", "="))
        self.let2_1.setText(_translate("Fast_type", "ф"))
        self.n8.setText(_translate("Fast_type", "8"))
        self.n6.setText(_translate("Fast_type", "6"))
        self.let3_3.setText(_translate("Fast_type", "с"))
        self.menu.setText(_translate("Fast_type", "Menu"))
        self.tab.setText(_translate("Fast_type", "Tab"))
        self.text_2.setText(_translate("Fast_type", "Просто текст"))
        self.label_2.setText(_translate("Fast_type", "Уровень 2"))
        self.label_3.setText(_translate("Fast_type", "00:00"))


    def func_start1(self):
        if self.button_start1.text() == 'Старт':
            self.timer1.start()
            self.button_start1.setText('Стоп')
        else:
            self.timer1.stop()
            self.button_start1.setText('Старт')
            self.button_start1.hide()

    def func_start2(self):
        if self.button_start2.text() == 'Старт':
            self.timer2.start()
            self.button_start2.setText('Стоп')
        else:
            self.timer2.stop()
            self.button_start2.setText('Старт')
            self.button_start2.hide()

    def displayTime1(self):
        f_temp = datetime.utcfromtimestamp(self.temp1).strftime("%M:%S")
        self.label_4.setText(f_temp)
        self.temp1 += 1

    def displayTime2(self):
        f_temp = datetime.utcfromtimestamp(self.temp2).strftime("%M:%S")
        self.label_3.setText(f_temp)
        self.temp2 += 1


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Fast_type = QtWidgets.QMainWindow()
    ui = Ui_Fast_type()
    ui.setupUi(Fast_type)
    Fast_type.show()
    sys.exit(app.exec_())
